#!/usr/bin/env python3
"""Gera o PLAY_CONSOLE.md (seção 14 do AGENTS.md) a partir de config/publisher.json
e data/ads.json: respostas prontas para os formulários do Google Play Console.

Uso: python3 tools/store/gen_play_console.py
(o tools/sync_publisher.py também roda este script ao aplicar o publisher.json)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main():
    pub = json.loads((ROOT / "config/publisher.json").read_text(encoding="utf-8"))
    ads = json.loads((ROOT / "data/ads.json").read_text(encoding="utf-8"))
    aud = ads.get("audience", {})
    age = int(pub.get("audience_min_age", 13))
    site = pub["website"]
    L = []
    a = L.append
    a(f"# Google Play Console — {pub['store_title']}")
    a("")
    a("Gerado por `tools/store/gen_play_console.py` a partir de `config/publisher.json` e `data/ads.json`. "
      "Não edite à mão: mude o `publisher.json` e rode `python3 tools/sync_publisher.py`.")
    a("")
    a("## 1. Criar o app")
    a("")
    a("| Campo | Resposta |")
    a("|---|---|")
    a(f"| Nome do app | {pub['store_title']} |")
    a("| Idioma padrão | Português (Brasil) – pt-BR |")
    a("| App ou jogo | Jogo |")
    a("| Gratuito ou pago | Gratuito |")
    a(f"| Pacote | `{pub['package_name']}` |")
    a(f"| Desenvolvedor | {pub['producer']} ({pub['responsible']}) |")
    a(f"| E-mail de contato | {pub['contact_email']} |")
    a(f"| Site | {site} |")
    a("| Categoria | Jogos → RPG |")
    a("| Tags sugeridas | RPG, Coleta de criaturas, Aventura, Pixel art, Single player, Offline |")
    a("")
    a("## 2. Conteúdo do app (Política → Conteúdo do app)")
    a("")
    a("### Política de privacidade")
    a(f"- URL: **{pub['privacy_policy_url']}**")
    a(f"- Arquivos para a raiz de {site}: a pasta `site/` (index, política em PT/EN/ES e `app-ads.txt`). "
      "O artefato `site-da-produtora` do build de release traz a mesma pasta já com o ID de editor no `app-ads.txt`.")
    a(f"- Informe {site} como site do desenvolvedor na Play Console (é onde o AdMob procura o `{site}/app-ads.txt`).")
    a("- Passo a passo pelo navegador: `docs/PUBLICAR_PELO_NAVEGADOR.md`.")
    a("")
    a("### Acesso ao app")
    a("- **Todas as funcionalidades estão disponíveis sem acesso especial.** Não há login, conta ou assinatura.")
    a("")
    a("### Anúncios")
    a("- **O app contém anúncios: Sim** (Google AdMob: banner nos menus, intersticial após vitórias e premiados opcionais).")
    a("")
    a("### Classificação do conteúdo (questionário IARC)")
    a("| Pergunta | Resposta |")
    a("|---|---|")
    a("| Categoria | Jogo |")
    a("| Violência | **Sim, violência de fantasia leve**: criaturas esqueleto estilizadas batalham por turnos; sem sangue, sem morte mostrada, sem violência realista contra humanos |")
    a("| Sangue / gore | Não |")
    a("| Medo / horror | Não (esqueletos são fofos e fazem aniversário) |")
    a("| Sexualidade / nudez | Não |")
    a("| Linguagem imprópria | Não |")
    a("| Drogas, álcool, tabaco | Não |")
    a("| Apostas / jogos de azar simulados | Não (não há compra de itens aleatórios nem caixas de recompensa) |")
    a("| Interação entre usuários / chat | Não |")
    a("| Compartilha localização com outros usuários | Não |")
    a("| Compras digitais | Não |")
    a("| Conteúdo gerado por usuários | Não |")
    a("- Resultado esperado: classificação livre/10+ conforme a região (ClassInd, ESRB E10+, PEGI 7).")
    a("")
    a("### Público-alvo e conteúdo")
    a(f"- **Faixas etárias:** {age}–15, 16–17 e 18+ (público-alvo {age}+).")
    a("- O app **não** é destinado a crianças e não participa do programa Famílias.")
    a(f"- Pode atrair crianças sem querer? **Não** — o tom é de aventura para {age}+, e os anúncios seguem a configuração abaixo.")
    a(f"- Configuração de anúncios no código (`data/ads.json`): `tagForChildDirectedTreatment = {str(aud.get('child_directed', False)).lower()}`, "
      f"`tagForUnderAgeOfConsent = {str(aud.get('under_age_of_consent', False)).lower()}`, conteúdo máximo dos anúncios **{aud.get('max_rating', 'PG')}**.")
    a("- O teto **PG** do AdMob mantém os anúncios dentro da classificação do jogo (10+/PEGI 7): a política de anúncios do Google Play "
      "pede que os anúncios sejam adequados à classificação do app. No AdMob, em *Bloqueio de controles → Classificação de conteúdo*, "
      "escolha também **PG** para valer no servidor.")
    a("")
    a("### ID de publicidade")
    a("- **O app usa o ID de publicidade: Sim.** Finalidade: **Publicidade ou marketing** e **Análise** (feitas pelo SDK do Google AdMob).")
    a("- O manifesto declara `com.google.android.gms.permission.AD_ID` (targetSdk 36).")
    a("")
    a("### Apps de notícias, governamentais, financeiros, de saúde e de COVID-19")
    a("- Não se aplica a nenhum deles (responda **Não** em todos).")
    a("")
    a("## 3. Segurança dos dados")
    a("")
    a("O jogo não tem servidor nem conta e não coleta dados próprios: o save fica só no aparelho. "
      "Os dados abaixo são coletados pelo **SDK do Google AdMob** (incluindo o consentimento UMP).")
    a("")
    a("| Pergunta | Resposta |")
    a("|---|---|")
    a("| O app coleta ou compartilha algum dos tipos de dados obrigatórios? | **Sim** |")
    a("| Todos os dados coletados são criptografados em trânsito? | **Sim** |")
    a("| Os usuários podem pedir a exclusão dos dados? | Não há conta nem dados guardados pelo app; o ID de publicidade é redefinido nas configurações do Android. Responda **Não** (não há mecanismo próprio) |")
    a("| O app permite criar conta? | **Não** |")
    a("")
    a("| Tipo de dado | Coletado | Compartilhado | Opcional? | Finalidades |")
    a("|---|---|---|---|---|")
    a("| **Identificadores do dispositivo ou outros IDs** (ID de publicidade) | Sim | Sim | Não | Publicidade ou marketing; Análise; Prevenção de fraudes, segurança e conformidade |")
    a("| **Interações no app** (atividade do app) | Sim | Sim | Não | Publicidade ou marketing; Análise |")
    a("| **Diagnóstico** (registros de falhas e desempenho do SDK) | Sim | Sim | Não | Análise; Prevenção de fraudes, segurança e conformidade |")
    a("| **Local aproximado** (derivado do IP) | Sim | Sim | Não | Publicidade ou marketing; Análise; Prevenção de fraudes |")
    a("")
    a("Nada é coletado para funcionalidade do app nem para personalização própria. Não há dados pessoais, financeiros, de saúde, mensagens, fotos, arquivos ou contatos.")
    a("")
    a("## 4. Ficha da loja")
    a("")
    a("| Idioma | Textos | Gráficos |")
    a("|---|---|---|")
    for lang, name in [("pt_BR", "Português (Brasil) – pt-BR"), ("en", "Inglês (Estados Unidos) – en-US"), ("es", "Espanhol (América Latina) – es-419")]:
        a(f"| {name} | `store/listing.{lang}.md` | `store/screenshots/{lang}/` (7 capturas 1280×720) |")
    a("")
    a("- Ícone 512×512: `store/graphics/icon_512.png` · Gráfico de destaque 1024×500: `store/graphics/feature_1024x500.png`.")
    a("- Os textos não citam outras marcas (o `tools/store/gen_store_docs.py` confere).")
    a("- As capturas mostram o jogo atual: depois de mudar a interface ou o conteúdo mostrado, refaça com `python3 tools/store/gen_store_shots.py`.")
    a("")
    a("## 5. Versões e testes")
    a("")
    a("1. Configure os Secrets do GitHub (veja `docs/BUILD.md`): keystore e os 4 IDs reais do AdMob.")
    a("2. Preencha os campos entre colchetes do `config/publisher.json` e rode `python3 tools/sync_publisher.py`. O release falha enquanto houver placeholders.")
    a(f"3. Crie a tag `v{pub['version_name']}` (ou rode o workflow com *release* marcado) e baixe o artefato `esqueletons-release-aab`.")
    a("4. Ative a **Assinatura de apps do Google Play** e envie o `.aab` para a faixa de **teste fechado**.")
    a("5. **Conta pessoal nova (criada depois de 13/11/2023):** o Google exige um **teste fechado com pelo menos 12 testadores, "
      "ativos por 14 dias seguidos**, antes de liberar a produção. Convide os testadores por e-mail ou Grupo do Google logo no começo.")
    a("6. Depois do teste fechado, peça o acesso à produção respondendo ao questionário sobre o teste.")
    a("")
    a("## 6. AdMob")
    a("")
    a(f"- Crie o app no AdMob (Android, `{pub['package_name']}`) e 3 blocos: banner, intersticial e premiado.")
    a(f"- ID do editor para o `app-ads.txt`: `{pub['admob']['publisher_id']}`.")
    a("- Em **Privacidade e mensagens**, crie as mensagens de consentimento (GDPR e estados dos EUA). O jogo já mostra o formulário UMP antes de iniciar os anúncios e "
      "reabre-o em *Configurações → Privacidade e anúncios*.")
    a("- Os IDs de teste do Google ficam no build de debug; os reais só entram no release, via Secrets.")
    a("")
    (ROOT / "PLAY_CONSOLE.md").write_text("\n".join(L), encoding="utf-8")
    print("PLAY_CONSOLE.md gerado")


if __name__ == "__main__":
    main()
