"""Bíblia de criaturas (seção 8 do AGENTS.md) — fonte única do Bestiário.

Daqui saem: docs/BESTIARIO.md, i18n/species.csv (nomes e entradas do Ossário),
data/species.json (identidade, crescimento, atributos e sprites) e os sprites
(tools/art/gen_skeletons.py). Para mudar um esqueleto, mude aqui e rode
tools/bestiary/build.py.

Cada linha: conceito (profissão/papel em vida + objeto + habitat), silhueta,
arco de crescimento (Bebê → Adolescente → Adulto), personalidade, comportamento
no mapa, tipo, região, raridade, idades de crescimento, golpe assinatura,
nomes nos 3 idiomas e entrada do Ossário por estágio (máx. 2 frases).

Papel (role) define o perfil de atributos usado em build.py:
  tanque, bruto, veloz, equilibrado, mago, suporte, astuto.
"""

LINES = [
    # ------------------------------------------------------------ PRAIA / VILA MARÉ (Prólogo)
    {
        "id": "grumete", "type": "fisico", "region": "praia", "rarity": "incomum", "growth": [16, 36],
        "role": "bruto", "behavior": "chase", "gender": "m", "starter": "Taro",
        "concept": "Esqueleto de grumete dos barcos de pesca da Vila Maré, que nunca larga o remo.",
        "silhouette": "Remo vertical maior que o corpo ao lado direito; chapéu muda de touca de pompom para bandana e para quepe de capitão.",
        "arc": "Bebê de touca e camiseta listrada com um remo de brinquedo → Adolescente de bandana e colete vermelho com um remo de verdade apoiado no chão → Adulto de casaco de lona e quepe, com o remo duplo atravessado nas costas como uma arma.",
        "personality": "Teimoso, leal, barulhento",
        "signature": {"id": "remada_dupla", "pt": "Remada Dupla", "en": "Double Stroke", "es": "Remada Doble"},
        "stages": [
            {"pt": "Remito", "en": "Oarlet", "es": "Remiño",
             "entry": {"pt": "Treina remadas no ar enquanto dorme. Ainda confunde o remo com uma colher.",
                       "en": "It practices rowing in its sleep. It still mistakes its oar for a spoon.",
                       "es": "Practica remadas mientras duerme. Aún confunde el remo con una cuchara."}},
            {"pt": "Vogaréu", "en": "Strokeby", "es": "Bogador",
             "entry": {"pt": "Desafia qualquer um para uma corrida de barco. Perde a calma, nunca o ritmo.",
                       "en": "It challenges anyone to a boat race. It loses its temper, never its rhythm.",
                       "es": "Reta a cualquiera a una carrera de botes. Pierde la calma, nunca el ritmo."}},
            {"pt": "Timonaço", "en": "Helmsbone", "es": "Timonazo",
             "entry": {"pt": "Já atravessou tempestades sem barco, só com o remo. A tripulação dele são as ondas.",
                       "en": "It has crossed storms with no boat, only its oar. The waves are its crew.",
                       "es": "Ha cruzado tormentas sin barco, solo con su remo. Las olas son su tripulación."}},
        ],
    },
    {
        "id": "faroleira", "type": "magico", "region": "praia", "rarity": "incomum", "growth": [16, 36],
        "role": "mago", "behavior": "patrol", "gender": "f", "starter": "Lia",
        "concept": "Esqueleto de aprendiz de faroleira do velho farol apagado da praia, guiada por uma lamparina.",
        "silhouette": "Luz sempre à direita e acima do corpo: lamparina na mão, depois lanterna de prisma nas costas, depois o próprio farol como coroa e um cajado-lente.",
        "arc": "Bebê de touca de pano com uma lamparina pequena → Adolescente com a lanterna de prisma presa às costas e capa curta → Adulta de manto violeta, coroa-farol acesa e cajado com lente.",
        "personality": "Curiosa, sonhadora, corajosa",
        "signature": {"id": "facho_do_farol", "pt": "Facho do Farol", "en": "Beacon Beam", "es": "Haz del Faro"},
        "stages": [
            {"pt": "Lumiça", "en": "Glimmet", "es": "Chispela",
             "entry": {"pt": "Acende a lamparina quando tem medo do escuro, ou seja, sempre.",
                       "en": "It lights its lamp whenever it fears the dark, which is always.",
                       "es": "Enciende su lámpara cuando teme a la oscuridad, o sea, siempre."}},
            {"pt": "Prismela", "en": "Prismae", "es": "Prismina",
             "entry": {"pt": "Desvia a luz do prisma para escrever recados no céu. Ninguém consegue ler a letra dela.",
                       "en": "It bends prism light to write notes across the sky. Nobody can read its handwriting.",
                       "es": "Desvía la luz del prisma para escribir mensajes en el cielo. Nadie entiende su letra."}},
            {"pt": "Faroleza", "en": "Beaconne", "es": "Farolesa",
             "entry": {"pt": "A coroa dela gira devagar a noite inteira. Barcos perdidos chegam à praia seguindo esse brilho.",
                       "en": "Its crown turns slowly all night. Lost boats reach shore by following its glow.",
                       "es": "Su corona gira despacio toda la noche. Los barcos perdidos llegan a la orilla siguiendo su brillo."}},
        ],
    },
    {
        "id": "marisqueiro", "type": "veneno", "region": "praia", "rarity": "comum", "growth": [14, 34],
        "role": "astuto", "behavior": "shy", "gender": "m",
        "concept": "Esqueleto de catador de mariscos das pedras da praia, que aprendeu a usar os espinhos dos ouriços.",
        "silhouette": "Corpo largo e baixo coberto de espinhos que crescem a cada estágio; concha na cabeça vira capacete de ouriço espetado.",
        "arc": "Bebê com uma concha na cabeça e um baldinho → Adolescente com luvas de ouriço e uma rede de catar → Adulto com armadura de ouriços e um tridente de espinhos.",
        "personality": "Desconfiado, paciente, espinhoso",
        "signature": {"id": "chuva_de_espinhos", "pt": "Chuva de Espinhos", "en": "Spine Shower", "es": "Lluvia de Púas"},
        "stages": [
            {"pt": "Mariscote", "en": "Shellby", "es": "Almejito",
             "entry": {"pt": "Esconde-se dentro da concha quando alguém olha. A concha é bem menor que ele.",
                       "en": "It hides inside its shell when watched. The shell is much smaller than it is.",
                       "es": "Se esconde en su concha cuando lo miran. La concha es mucho más pequeña que él."}},
            {"pt": "Ouriçal", "en": "Urchip", "es": "Erizón",
             "entry": {"pt": "Usa luvas de ouriço para cumprimentar. Por isso ninguém aperta a mão dele.",
                       "en": "It wears urchin gloves to say hello. That is why nobody shakes its hand.",
                       "es": "Saluda con guantes de erizo. Por eso nadie le da la mano."}},
            {"pt": "Espinhardo", "en": "Spinnacle", "es": "Pinchardo",
             "entry": {"pt": "Fica imóvel nas pedras até a maré baixar. Quem pisa nele sente o veneno por três dias.",
                       "en": "It sits still on the rocks until low tide. Whoever steps on it feels the venom for three days.",
                       "es": "Se queda quieto en las rocas hasta la marea baja. Quien lo pisa siente el veneno tres días."}},
        ],
    },
    {
        "id": "rendeira", "type": "cura", "region": "praia", "rarity": "comum", "growth": [14, 34],
        "role": "suporte", "behavior": "circle", "gender": "f",
        "concept": "Esqueleto de rendeira de redes da Vila Maré, que remenda redes e, com o mesmo fio, os amigos feridos.",
        "silhouette": "Formato de sino por causa da saia de rede; agulha de rede longa e novelo; rede vira xale e depois um tear nas costas como asas.",
        "arc": "Bebê enrolada num novelo de fio → Adolescente com a agulha grande e a rede jogada nos ombros → Adulta com um tear portátil nas costas e a rede brilhante aberta como asas.",
        "personality": "Atenciosa, tagarela, caprichosa",
        "signature": {"id": "remendo_de_rede", "pt": "Remendo de Rede", "en": "Net Mend", "es": "Remiendo de Red"},
        "stages": [
            {"pt": "Novelita", "en": "Knotling", "es": "Ovillita",
             "entry": {"pt": "Rola pela areia quando se enrosca no próprio fio. Desenrolar leva a tarde toda.",
                       "en": "It rolls across the sand when tangled in its own yarn. Untangling it takes all afternoon.",
                       "es": "Rueda por la arena cuando se enreda en su hilo. Desenredarla lleva toda la tarde."}},
            {"pt": "Tramela", "en": "Shuttla", "es": "Tramona",
             "entry": {"pt": "Costura rasgos em velas, redes e mangas, sem pedir licença.",
                       "en": "It stitches tears in sails, nets and sleeves without asking permission.",
                       "es": "Cose rotos en velas, redes y mangas sin pedir permiso."}},
            {"pt": "Redentora", "en": "Tapestrix", "es": "Redencia",
             "entry": {"pt": "Tece com fios de luz da lua. Dizem que remenda até promessas quebradas.",
                       "en": "It weaves with threads of moonlight. Some say it can mend even broken promises.",
                       "es": "Teje con hilos de luz de luna. Dicen que remienda hasta promesas rotas."}},
        ],
    },
    # ------------------------------------------------------------ BOSQUE DAS RAÍZES (Ato 1)
    {
        "id": "lenhador", "type": "fisico", "region": "bosque", "rarity": "comum", "growth": [18, 40],
        "role": "bruto", "behavior": "chase", "gender": "m",
        "concept": "Esqueleto de lenhador do Bosque das Raízes que só derruba árvores mortas, e defende as vivas no machado.",
        "silhouette": "Ferramenta de corte cada vez mais pesada à direita; ombros crescem até virar um tronco no ombro; barba de musgo no adulto.",
        "arc": "Bebê de gorro xadrez arrastando um graveto → Adolescente com machado e mochila de toras → Adulto de barba de musgo carregando um tronco inteiro como clava.",
        "personality": "Teimoso, protetor, ruidoso",
        "signature": {"id": "golpe_de_tora", "pt": "Golpe de Tora", "en": "Log Slam", "es": "Golpe de Tronco"},
        "stages": [
            {"pt": "Lasquinho", "en": "Twiglet", "es": "Astillo",
             "entry": {"pt": "Bate o graveto em tudo para ver o que é oco. Inclusive na própria cabeça.",
                       "en": "It taps its twig on everything to find what is hollow, its own head included.",
                       "es": "Golpea todo con su ramita para ver qué está hueco. Incluida su propia cabeza."}},
            {"pt": "Toreiro", "en": "Hatchley", "es": "Hachón",
             "entry": {"pt": "Empilha toras em torres perfeitas e fica bravo se o vento derruba.",
                       "en": "It stacks logs into perfect towers and gets cross when the wind knocks them down.",
                       "es": "Apila troncos en torres perfectas y se enoja si el viento las derriba."}},
            {"pt": "Troncalho", "en": "Timbrawl", "es": "Troncazo",
             "entry": {"pt": "O musgo da barba dele tem vida própria. Um golpe da tora abre clareiras.",
                       "en": "The moss in its beard has a life of its own. One swing of its log opens a clearing.",
                       "es": "El musgo de su barba tiene vida propia. Un golpe de su tronco abre claros."}},
        ],
    },
    {
        "id": "herborista", "type": "cura", "region": "bosque", "rarity": "comum", "growth": [18, 40],
        "role": "suporte", "behavior": "shy", "gender": "f",
        "concept": "Esqueleto de herborista do bosque que colhe raízes medicinais e acaba virando parte do jardim.",
        "silhouette": "Algo verde brotando de cima: broto na cabeça, depois cesto de raízes, e por fim uma arvorezinha saindo das costelas com coroa de flores.",
        "arc": "Bebê com um broto de duas folhas na cabeça → Adolescente de avental com cesto de raízes no braço → Adulta com uma arvorezinha crescendo entre as costelas e coroa de flores.",
        "personality": "Calma, gentil, distraída",
        "signature": {"id": "seiva_viva", "pt": "Seiva Viva", "en": "Living Sap", "es": "Savia Viva"},
        "stages": [
            {"pt": "Brotim", "en": "Sproutle", "es": "Brotín",
             "entry": {"pt": "Fica parada ao sol para o broto crescer. Às vezes esquece de sair da chuva.",
                       "en": "It stands in the sun so its sprout will grow. Sometimes it forgets to get out of the rain.",
                       "es": "Se queda quieta al sol para que crezca su brote. A veces olvida salir de la lluvia."}},
            {"pt": "Raizela", "en": "Rootessa", "es": "Raicera",
             "entry": {"pt": "Sabe o nome de cada raiz do bosque e o chá certo para cada dor.",
                       "en": "It knows the name of every root in the woods and the right tea for every ache.",
                       "es": "Sabe el nombre de cada raíz del bosque y el té justo para cada dolor."}},
            {"pt": "Floralma", "en": "Bloomsoul", "es": "Floránima",
             "entry": {"pt": "A árvore dentro dela floresce quando alguém por perto se cura. Abelhas a seguem por todo canto.",
                       "en": "The tree inside it blooms whenever someone nearby heals. Bees follow it everywhere.",
                       "es": "El árbol en su interior florece cuando alguien cerca se cura. Las abejas la siguen a todas partes."}},
        ],
    },
    {
        "id": "cogumeleiro", "type": "veneno", "region": "bosque", "rarity": "incomum", "growth": [20, 42],
        "role": "astuto", "behavior": "patrol", "gender": "m",
        "concept": "Esqueleto de colhedor de cogumelos que provou o cogumelo errado e passou a soltar esporos.",
        "silhouette": "Chapéu de cogumelo que cresce até virar um guarda-chuva largo que cobre o corpo todo; esporos flutuando em volta.",
        "arc": "Bebê com um cogumelinho pintado na cabeça → Adolescente com cogumelos brotando nas costas e soltando esporos → Adulto sob um chapéu-cogumelo enorme, com cajado de micélio.",
        "personality": "Sonolento, misterioso, guloso",
        "signature": {"id": "nuvem_de_esporos", "pt": "Nuvem de Esporos", "en": "Spore Cloud", "es": "Nube de Esporas"},
        "stages": [
            {"pt": "Fungote", "en": "Mushkin", "es": "Hongüito",
             "entry": {"pt": "Espirra esporos quando ri. Ri de quase tudo.",
                       "en": "It sneezes spores when it laughs. It laughs at almost everything.",
                       "es": "Estornuda esporas cuando ríe. Se ríe de casi todo."}},
            {"pt": "Esporito", "en": "Sporeling", "es": "Esporín",
             "entry": {"pt": "Dorme encostado em troncos úmidos e acorda com cogumelos novos nas costas.",
                       "en": "It naps against damp logs and wakes with new mushrooms on its back.",
                       "es": "Duerme junto a troncos húmedos y despierta con hongos nuevos en la espalda."}},
            {"pt": "Cogumestre", "en": "Fungaroth", "es": "Setarca",
             "entry": {"pt": "Debaixo do chapéu dele nunca chove. Quem fica tempo demais ali dorme por um dia inteiro.",
                       "en": "It never rains beneath its cap. Whoever lingers there sleeps for a whole day.",
                       "es": "Bajo su sombrero nunca llueve. Quien se queda allí demasiado duerme un día entero."}},
        ],
    },
    {
        "id": "flautista", "type": "magico", "region": "bosque", "rarity": "raro", "growth": [22, 46],
        "role": "veloz", "behavior": "fast", "gender": "m",
        "concept": "Esqueleto de flautista da floresta que chama vaga-lumes com uma flauta de osso.",
        "silhouette": "Flauta sempre na horizontal diante do rosto; vaga-lumes em volta; o adulto ganha chifres de galhos e capa de folhas.",
        "arc": "Bebê com uma flautinha e um vaga-lume pousado na cabeça → Adolescente com flauta longa e um enxame de vaga-lumes em órbita → Adulto com chifres de galho, capa de folhas e flauta-cajado.",
        "personality": "Brincalhão, vaidoso, inquieto",
        "signature": {"id": "melodia_vagalume", "pt": "Melodia Vaga-lume", "en": "Firefly Tune", "es": "Melodía Luciérnaga"},
        "stages": [
            {"pt": "Flautim", "en": "Pipkin", "es": "Pitillo",
             "entry": {"pt": "Só sabe uma nota. Toca essa nota com muito sentimento.",
                       "en": "It only knows one note. It plays that note with great feeling.",
                       "es": "Solo sabe una nota. La toca con mucho sentimiento."}},
            {"pt": "Vagalú", "en": "Glowfife", "es": "Luciérnago",
             "entry": {"pt": "Os vaga-lumes dançam no ritmo da flauta. Quando erra a nota, eles apagam de vergonha.",
                       "en": "Fireflies dance to its flute. When it misses a note, they dim in embarrassment.",
                       "es": "Las luciérnagas bailan al ritmo de su flauta. Si falla una nota, se apagan de vergüenza."}},
            {"pt": "Silvanor", "en": "Sylvarch", "es": "Selvanor",
             "entry": {"pt": "Rege a floresta à noite como uma orquestra. As árvores se curvam para ouvir.",
                       "en": "It conducts the forest at night like an orchestra. The trees lean in to listen.",
                       "es": "Dirige el bosque de noche como una orquesta. Los árboles se inclinan para escuchar."}},
        ],
    },
    # ------------------------------------------------------------ MINAS DE CINZAS (Ato 2)
    {
        "id": "mineiro", "type": "fisico", "region": "minas", "rarity": "comum", "growth": [24, 46],
        "role": "tanque", "behavior": "patrol", "gender": "m",
        "concept": "Esqueleto de mineiro das Minas de Cinzas, do balde de ajudante à armadura de pedra.",
        "silhouette": "Balde na cabeça vira capacete com picareta no ombro e, no adulto, um corpo largo coberto de placas de pedra.",
        "arc": "Bebê ajudante com um balde na cabeça → Adolescente mineiro de capacete com picareta → Adulto mestre de minas com armadura de pedra e picareta dupla.",
        "personality": "Trabalhador, sério, resistente",
        "signature": {"id": "desmoronar", "pt": "Desmoronar", "en": "Cave-In", "es": "Derrumbe"},
        "stages": [
            {"pt": "Baldinho", "en": "Pailet", "es": "Cubetín",
             "entry": {"pt": "Usa o balde como capacete e como cama. Ainda não decidiu qual é o certo.",
                       "en": "It uses its pail as a helmet and as a bed. It has not decided which is right.",
                       "es": "Usa la cubeta de casco y de cama. Aún no decide cuál es lo correcto."}},
            {"pt": "Picaréu", "en": "Pickard", "es": "Picador",
             "entry": {"pt": "Escuta a rocha antes de bater. Diz que cada pedra tem uma veia preferida.",
                       "en": "It listens to the rock before striking. It says every stone has a favorite vein.",
                       "es": "Escucha la roca antes de golpear. Dice que cada piedra tiene una veta favorita."}},
            {"pt": "Rochedão", "en": "Bouldron", "es": "Peñascón",
             "entry": {"pt": "As placas de pedra da armadura foram arrancadas da mina mais funda. Desmoronamentos o contornam.",
                       "en": "Its armor plates were torn from the deepest mine. Cave-ins step around it.",
                       "es": "Las placas de su armadura vienen de la mina más profunda. Los derrumbes lo esquivan."}},
        ],
    },
    {
        "id": "ferreiro", "type": "magico", "region": "minas", "rarity": "incomum", "growth": [24, 46],
        "role": "mago", "behavior": "patrol", "gender": "m",
        "concept": "Esqueleto de ferreiro das forjas das Minas de Cinzas, cujo fogo nunca apaga.",
        "silhouette": "Avental de couro grande; martelo erguido à direita; no adulto, as costelas viram uma forja acesa no peito.",
        "arc": "Bebê com martelinho e avental de couro grande demais → Adolescente com bigorna nas costas e fole na mão → Adulto com a forja acesa dentro das costelas e um martelo de lava.",
        "personality": "Orgulhoso, esquentado, generoso",
        "signature": {"id": "martelo_de_brasa", "pt": "Martelo de Brasa", "en": "Ember Hammer", "es": "Martillo de Brasa"},
        "stages": [
            {"pt": "Faisquim", "en": "Sparkit", "es": "Chispín",
             "entry": {"pt": "Bate o martelinho em pedras para ver faíscas. Aplaude cada uma.",
                       "en": "It taps stones with its little hammer to make sparks. It applauds every one.",
                       "es": "Golpea piedras con su martillito para ver chispas. Aplaude cada una."}},
            {"pt": "Bigornel", "en": "Anvillo", "es": "Yunquero",
             "entry": {"pt": "Carrega a bigorna para todo lado, caso precise consertar algo de repente.",
                       "en": "It carries its anvil everywhere in case something suddenly needs fixing.",
                       "es": "Lleva su yunque a todas partes por si algo necesita arreglo de repente."}},
            {"pt": "Forjalma", "en": "Kilnhart", "es": "Fraguador",
             "entry": {"pt": "A forja no peito dele aquece a mina inteira no inverno. Martela feitiços como quem martela ferro.",
                       "en": "The forge in its chest warms the whole mine in winter. It hammers spells like iron.",
                       "es": "La fragua de su pecho calienta toda la mina en invierno. Forja hechizos como quien forja hierro."}},
        ],
    },
    {
        "id": "gasista", "type": "veneno", "region": "minas", "rarity": "comum", "growth": [24, 46],
        "role": "equilibrado", "behavior": "circle", "gender": "m",
        "concept": "Esqueleto de vigia de gás das galerias, que de tanto farejar o gás das minas passou a produzi-lo.",
        "silhouette": "Máscara de gás com um filtro redondo na frente; tanque nas costas que cresce até virar chaminés soltando névoa verde.",
        "arc": "Bebê com uma mascarinha e uma gaiolinha vazia → Adolescente com um tanque de gás nas costas e uma mangueira → Adulto com máscara de foles e duas chaminés de névoa verde.",
        "personality": "Ansioso, metódico, abafado",
        "signature": {"id": "vazamento", "pt": "Vazamento", "en": "Gas Leak", "es": "Fuga de Gas"},
        "stages": [
            {"pt": "Gasito", "en": "Whiffle", "es": "Humito",
             "entry": {"pt": "Fareja tudo antes de entrar. A gaiolinha dele está sempre vazia, e ele prefere assim.",
                       "en": "It sniffs everything before entering. Its little cage is always empty, and it likes it that way.",
                       "es": "Olfatea todo antes de entrar. Su jaulita siempre está vacía, y así la prefiere."}},
            {"pt": "Fumarel", "en": "Fumehorn", "es": "Fumarón",
             "entry": {"pt": "O tanque das costas faz um apito agudo antes de vazar. Mineiros correm quando escutam.",
                       "en": "The tank on its back whistles shrilly before it leaks. Miners run when they hear it.",
                       "es": "El tanque de su espalda silba agudo antes de soltar gas. Los mineros corren al oírlo."}},
            {"pt": "Miasmor", "en": "Miasmar", "es": "Miasmón",
             "entry": {"pt": "As chaminés soltam uma névoa verde que cobre galerias inteiras. Ele mesmo respira por filtros.",
                       "en": "Its chimneys pour green fog over whole tunnels. It breathes only through filters.",
                       "es": "Sus chimeneas sueltan niebla verde sobre galerías enteras. Él mismo respira con filtros."}},
        ],
    },
    {
        "id": "aguadeiro", "type": "cura", "region": "minas", "rarity": "raro", "growth": [28, 50],
        "role": "tanque", "behavior": "shy", "gender": "m",
        "concept": "Esqueleto de aguadeiro que leva água fresca aos mineiros nas galerias quentes das Minas de Cinzas.",
        "silhouette": "Recipiente de água cada vez maior: cantil a tiracolo, carrinho com bilhas, e uma cisterna redonda nas costas com mangueiras.",
        "arc": "Bebê com um cantil maior que ele → Adolescente empurrando um carrinho com bilhas → Adulto com uma cisterna redonda nas costas e mangueiras de cura.",
        "personality": "Prestativo, tímido, refrescante",
        "signature": {"id": "jato_fresco", "pt": "Jato Fresco", "en": "Cool Spray", "es": "Chorro Fresco"},
        "stages": [
            {"pt": "Cantilho", "en": "Sippet", "es": "Cantimplín",
             "entry": {"pt": "Oferece água a todos, até às pedras. Diz que elas parecem cansadas.",
                       "en": "It offers water to everyone, even to rocks. It says they look tired.",
                       "es": "Ofrece agua a todos, hasta a las piedras. Dice que parecen cansadas."}},
            {"pt": "Bilheiro", "en": "Jugworth", "es": "Botijero",
             "entry": {"pt": "As bilhas tilintam no carrinho como um sino. Mineiros com sede seguem o som.",
                       "en": "The jugs on its cart clink like a bell. Thirsty miners follow the sound.",
                       "es": "Las botijas tintinean en su carro como una campana. Los mineros sedientos siguen el sonido."}},
            {"pt": "Cisternão", "en": "Cisterno", "es": "Aljibón",
             "entry": {"pt": "A cisterna das costas nunca esvazia. Um banho de mangueira dele apaga até fogo de forja.",
                       "en": "The cistern on its back never runs dry. One spray of its hose can put out a forge.",
                       "es": "El aljibe de su espalda nunca se vacía. Un chorro de su manguera apaga hasta una fragua."}},
        ],
    },
    # ------------------------------------------------------------ PÂNTANO VERDE-MUSGO (Ato 3)
    {
        "id": "lavadeira", "type": "veneno", "region": "pantano", "rarity": "comum", "growth": [30, 52],
        "role": "mago", "behavior": "patrol", "gender": "f",
        "concept": "Esqueleto de lavadeira do pântano com cesto de ervas venenosas, que lava a roupa na água parada.",
        "silhouette": "Bacia na cabeça vira cesto e tábua de lavar nas mãos; a adulta carrega uma tina-caldeirão nas costas com um varal de ervas por cima.",
        "arc": "Bebê com uma bacia na cabeça → Adolescente com cesto de ervas no quadril e tábua de lavar → Adulta com uma tina-caldeirão nas costas e um varal de ervas pendurado.",
        "personality": "Fofoqueira, prática, cheirosa",
        "signature": {"id": "anil_toxico", "pt": "Anil Tóxico", "en": "Toxic Bluing", "es": "Añil Tóxico"},
        "stages": [
            {"pt": "Tinhinha", "en": "Tubbit", "es": "Tinita",
             "entry": {"pt": "A bacia na cabeça vira barquinho quando o pântano enche.",
                       "en": "The basin on its head becomes a little boat when the swamp floods.",
                       "es": "La palangana de su cabeza se vuelve barquito cuando el pantano crece."}},
            {"pt": "Ervaçal", "en": "Herbwash", "es": "Hierbera",
             "entry": {"pt": "Esfrega as roupas com ervas do pântano. Elas ficam limpas, e um pouco venenosas.",
                       "en": "It scrubs clothes with swamp herbs. They come out clean, and slightly poisonous.",
                       "es": "Frota la ropa con hierbas del pantano. Queda limpia, y un poco venenosa."}},
            {"pt": "Caldeona", "en": "Cauldra", "es": "Caldreona",
             "entry": {"pt": "A tina dela borbulha dia e noite. O vapor verde espanta até mosquitos.",
                       "en": "Its tub bubbles day and night. The green steam scares off even mosquitoes.",
                       "es": "Su tina burbujea día y noche. El vapor verde espanta hasta a los mosquitos."}},
        ],
    },
    {
        "id": "palafiteiro", "type": "fisico", "region": "pantano", "rarity": "comum", "growth": [30, 52],
        "role": "tanque", "behavior": "patrol", "gender": "m",
        "concept": "Esqueleto de construtor de palafitas do Pântano Verde-Musgo, que fincou tantas estacas que acabou andando sobre elas.",
        "silhouette": "Cada vez mais alto: estaquinha no ombro, feixe de estacas e marreta, e por fim o adulto sobre pernas-de-pau com a marreta pesada.",
        "arc": "Bebê carregando uma estaquinha no ombro → Adolescente com um feixe de estacas nas costas e uma marreta → Adulto sobre pernas-de-pau, com marreta grande e chapéu de palha.",
        "personality": "Paciente, firme, desajeitado",
        "signature": {"id": "estaca_firme", "pt": "Estaca Firme", "en": "Pile Driver", "es": "Estaca Firme"},
        "stages": [
            {"pt": "Estaquim", "en": "Stakelet", "es": "Estaquín",
             "entry": {"pt": "Finca a estaquinha no chão e senta nela para descansar. Sempre afunda.",
                       "en": "It drives its little stake into the mud and sits on it to rest. It always sinks.",
                       "es": "Clava su estaquita en el barro y se sienta en ella a descansar. Siempre se hunde."}},
            {"pt": "Marretão", "en": "Malleteer", "es": "Mazón",
             "entry": {"pt": "Cada martelada dele crava uma estaca inteira. O pântano treme junto.",
                       "en": "Each blow of its mallet drives a whole stake. The swamp shakes along.",
                       "es": "Cada mazazo suyo clava una estaca entera. El pantano tiembla con él."}},
            {"pt": "Palafitor", "en": "Stiltwarden", "es": "Palafitero",
             "entry": {"pt": "Anda sobre as pernas-de-pau como se fossem dele. Do alto, vigia as casas que ajudou a erguer.",
                       "en": "It walks on its stilts as if they were its own legs. From up high it watches the houses it built.",
                       "es": "Camina sobre sus zancos como si fueran suyos. Desde lo alto vigila las casas que levantó."}},
        ],
    },
    {
        "id": "jardineiro_lirios", "type": "cura", "region": "pantano", "rarity": "incomum", "growth": [32, 56],
        "role": "suporte", "behavior": "circle", "gender": "m",
        "concept": "Esqueleto de jardineiro aquático que cuida dos lírios do pântano com um regador de cabaça.",
        "silhouette": "Folha redonda de lírio na cabeça que cresce até virar um guarda-sol enorme; regador de cabaça na mão.",
        "arc": "Bebê com uma folha de lírio como chapéu → Adolescente com regador de cabaça e flores nos ombros → Adulto sob uma folha gigante de lírio como escudo e guarda-sol.",
        "personality": "Sereno, poético, devagar",
        "signature": {"id": "orvalho_de_lirio", "pt": "Orvalho de Lírio", "en": "Lily Dew", "es": "Rocío de Lirio"},
        "stages": [
            {"pt": "Lirito", "en": "Lilypip", "es": "Nenufito",
             "entry": {"pt": "Boia de costas no pântano usando a folha como travesseiro.",
                       "en": "It floats on its back in the swamp, using its leaf as a pillow.",
                       "es": "Flota boca arriba en el pantano usando su hoja de almohada."}},
            {"pt": "Regalírio", "en": "Pondrella", "es": "Regadora",
             "entry": {"pt": "Rega cada flor do pântano uma por uma, cantando o nome delas.",
                       "en": "It waters each swamp flower one by one, singing their names.",
                       "es": "Riega cada flor del pantano una por una, cantando sus nombres."}},
            {"pt": "Aguapéu", "en": "Lotusage", "es": "Lotomayor",
             "entry": {"pt": "Debaixo da folha gigante dele as feridas fecham devagar. Viajantes fazem fila para descansar ali.",
                       "en": "Wounds slowly close beneath its giant leaf. Travelers line up to rest there.",
                       "es": "Bajo su hoja gigante las heridas se cierran despacio. Los viajeros hacen fila para descansar allí."}},
        ],
    },
    # ------------------------------------------------------------ CIDADE MURADA DE OSSÓRIO (Ato 4)
    {
        "id": "sentinela", "type": "fisico", "region": "ossorio", "rarity": "comum", "growth": [34, 58],
        "role": "tanque", "behavior": "patrol", "gender": "m",
        "concept": "Esqueleto de sentinela da muralha de Ossório, que nunca saiu do posto, nem depois de virar esqueleto.",
        "silhouette": "Escudo à esquerda que cresce de tampa de panela até um escudo-portão que cobre metade do corpo; lança com bandeira à direita.",
        "arc": "Bebê com uma tampa de panela de escudo → Adolescente de elmo com escudo de torre → Adulto com um escudo-portão gigante e lança com bandeira de Ossório.",
        "personality": "Disciplinado, rígido, fiel",
        "signature": {"id": "muralha_viva", "pt": "Muralha Viva", "en": "Living Wall", "es": "Muralla Viva"},
        "stages": [
            {"pt": "Tampinha", "en": "Liddle", "es": "Tapita",
             "entry": {"pt": "Bate continência para tudo que passa, inclusive para pombos.",
                       "en": "It salutes everything that walks by, pigeons included.",
                       "es": "Hace el saludo militar a todo lo que pasa, palomas incluidas."}},
            {"pt": "Broquel", "en": "Bulwarkin", "es": "Rodelón",
             "entry": {"pt": "Dorme de pé, encostado no escudo. Acorda com um único ruído estranho.",
                       "en": "It sleeps standing up against its shield. A single odd noise wakes it.",
                       "es": "Duerme de pie apoyado en su escudo. Un solo ruido extraño lo despierta."}},
            {"pt": "Bastião", "en": "Bastionel", "es": "Baluartón",
             "entry": {"pt": "O escudo dele já foi o portão de uma torre. Enquanto ele estiver de pé, a muralha não cai.",
                       "en": "Its shield was once a tower gate. While it stands, the wall does not fall.",
                       "es": "Su escudo fue la puerta de una torre. Mientras siga en pie, la muralla no cae."}},
        ],
    },
    {
        "id": "escriba", "type": "magico", "region": "ossorio", "rarity": "raro", "growth": [38, 62],
        "role": "mago", "behavior": "shy", "gender": "m",
        "concept": "Esqueleto de escriba dos arquivos de Ossório, que copia leis e feitiços sem parar.",
        "silhouette": "Pena de escrever enorme apontando para cima; um livro aberto flutuando; o adulto tem uma capa de pergaminhos e tinteiro como coroa.",
        "arc": "Bebê com uma pena de escrever espetada na cabeça → Adolescente com um livro aberto flutuando diante dele → Adulto com capa de pergaminhos e um tinteiro como coroa.",
        "personality": "Meticuloso, reservado, sabichão",
        "signature": {"id": "decreto_selado", "pt": "Decreto Selado", "en": "Sealed Decree", "es": "Decreto Sellado"},
        "stages": [
            {"pt": "Rabisquim", "en": "Scribbit", "es": "Garabatín",
             "entry": {"pt": "Escreve no ar com a pena da cabeça. Nunca termina uma frase.",
                       "en": "It writes in the air with the quill on its head. It never finishes a sentence.",
                       "es": "Escribe en el aire con la pluma de su cabeza. Nunca termina una frase."}},
            {"pt": "Escrivélio", "en": "Quillian", "es": "Plumario",
             "entry": {"pt": "O livro que o segue registra tudo o que ele vê. Inclusive o que você disse dele.",
                       "en": "The book that follows it records everything it sees, including what you said about it.",
                       "es": "El libro que lo sigue registra todo lo que ve. Incluso lo que dijiste de él."}},
            {"pt": "Pergamor", "en": "Tomeward", "es": "Pergaminor",
             "entry": {"pt": "Cada pergaminho da capa é uma lei antiga de Ossório. Quando lê uma em voz alta, ela acontece.",
                       "en": "Each scroll in its cape is an old law of Ossório. When it reads one aloud, it comes true.",
                       "es": "Cada pergamino de su capa es una ley antigua de Ossório. Cuando lee una en voz alta, se cumple."}},
        ],
    },
    {
        "id": "sineiro", "type": "cura", "region": "ossorio", "rarity": "incomum", "growth": [34, 58],
        "role": "suporte", "behavior": "circle", "gender": "m",
        "concept": "Esqueleto de sineiro da torre de Ossório, cujas badaladas acalmam e curam quem as ouve.",
        "silhouette": "Sino como peça central que cresce: sininho no pescoço, sino de mão erguido, e um sino enorme nas costas como uma carapaça.",
        "arc": "Bebê com um sininho no pescoço → Adolescente erguendo um sino de mão grande → Adulto com um sino de torre nas costas como uma carapaça e um badalo-cajado.",
        "personality": "Pontual, alegre, surdo de um lado",
        "signature": {"id": "badalada_serena", "pt": "Badalada Serena", "en": "Serene Toll", "es": "Campanada Serena"},
        "stages": [
            {"pt": "Tilintim", "en": "Dingle", "es": "Tilín",
             "entry": {"pt": "O sininho toca a cada passo, então nunca consegue se esconder.",
                       "en": "Its bell rings with every step, so it can never hide.",
                       "es": "Su campanita suena a cada paso, así que nunca puede esconderse."}},
            {"pt": "Badaleiro", "en": "Clapperton", "es": "Badajo",
             "entry": {"pt": "Toca o sino na hora certa, todos os dias. A cidade acerta os relógios por ele.",
                       "en": "It rings its bell on time every day. The city sets its clocks by it.",
                       "es": "Toca su campana a la hora exacta cada día. La ciudad ajusta sus relojes con él."}},
            {"pt": "Carrilhão", "en": "Carillon", "es": "Carillón",
             "entry": {"pt": "O sino das costas ressoa por dentro dos ossos. Uma badalada acalma uma briga inteira.",
                       "en": "The bell on its back resonates through its bones. One toll calms an entire brawl.",
                       "es": "La campana de su espalda resuena en sus huesos. Una campanada calma una pelea entera."}},
        ],
    },
    # ------------------------------------------------------------ PICOS GELADOS (Ato 5)
    {
        "id": "carregador", "type": "fisico", "region": "picos", "rarity": "comum", "growth": [40, 64],
        "role": "bruto", "behavior": "patrol", "gender": "m",
        "concept": "Esqueleto de carregador de montanha que leva mantimentos aos refúgios dos Picos Gelados.",
        "silhouette": "Mochila cada vez mais alta que o próprio corpo; no adulto, uma cargueira do tamanho de uma casinha e um cajado de gelo.",
        "arc": "Bebê de cachecol com uma mochilinha → Adolescente com uma mochila alta cheia de panelas e um piolet → Adulto com uma cargueira enorme nas costas e um cajado de gelo.",
        "personality": "Incansável, quieto, confiável",
        "signature": {"id": "avalanche_de_carga", "pt": "Avalanche de Carga", "en": "Cargo Avalanche", "es": "Alud de Carga"},
        "stages": [
            {"pt": "Mochilim", "en": "Packlet", "es": "Mochilín",
             "entry": {"pt": "Leva na mochila uma pedra de estimação. Diz que é para treinar.",
                       "en": "It carries a pet rock in its backpack. It says it is for training.",
                       "es": "Lleva una piedra mascota en la mochila. Dice que es para entrenar."}},
            {"pt": "Cargueiro", "en": "Haulster", "es": "Cargadón",
             "entry": {"pt": "As panelas da mochila batem no ritmo dos passos. É assim que os refúgios sabem que a sopa está chegando.",
                       "en": "The pots on its pack clang with each step. That is how shelters know soup is coming.",
                       "es": "Las ollas de su mochila suenan a cada paso. Así saben los refugios que llega la sopa."}},
            {"pt": "Alpinor", "en": "Summitor", "es": "Cumbrero",
             "entry": {"pt": "Já subiu todos os picos com a casa nas costas. Quando para, monta um abrigo para quem precisar.",
                       "en": "It has climbed every peak with a house on its back. When it stops, it builds a shelter for anyone in need.",
                       "es": "Ha subido todas las cumbres con una casa a cuestas. Cuando se detiene, arma un refugio para quien lo necesite."}},
        ],
    },
    {
        "id": "escultor", "type": "magico", "region": "picos", "rarity": "incomum", "growth": [40, 64],
        "role": "veloz", "behavior": "fast", "gender": "m",
        "concept": "Esqueleto de escultor de gelo dos Picos Gelados, que talha estátuas no gelo eterno com um cinzel.",
        "silhouette": "Cubo de gelo na cabeça; o adolescente ganha asas de gelo esculpidas; o adulto vira cristal, com coroa de pingentes.",
        "arc": "Bebê com um cubo de gelo de capacete e um cinzelzinho → Adolescente com asas de gelo que esculpiu para si mesmo → Adulto com armadura cristalina e coroa de pingentes de gelo.",
        "personality": "Perfeccionista, frio, sensível",
        "signature": {"id": "estatua_de_gelo", "pt": "Estátua de Gelo", "en": "Ice Statue", "es": "Estatua de Hielo"},
        "stages": [
            {"pt": "Gelinho", "en": "Cubbit", "es": "Hielito",
             "entry": {"pt": "Esculpe bonecos de neve parecidos com quem encontra. Os bonecos sempre saem sorrindo.",
                       "en": "It carves snowmen that look like whoever it meets. They always come out smiling.",
                       "es": "Esculpe muñecos de nieve parecidos a quien encuentra. Siempre salen sonriendo."}},
            {"pt": "Cinzelvo", "en": "Chiselle", "es": "Cincelón",
             "entry": {"pt": "Esculpiu as próprias asas e ainda não aprendeu a voar com elas. Plana nas descidas.",
                       "en": "It carved its own wings and has not learned to fly with them. It glides downhill.",
                       "es": "Esculpió sus propias alas y aún no aprende a volar con ellas. Planea en las bajadas."}},
            {"pt": "Cristalor", "en": "Glacior", "es": "Glaciarco",
             "entry": {"pt": "Transformou o próprio corpo em escultura. A luz que atravessa o cristal congela o que toca.",
                       "en": "It turned its own body into a sculpture. Light passing through its crystal freezes what it touches.",
                       "es": "Convirtió su propio cuerpo en escultura. La luz que cruza su cristal congela lo que toca."}},
        ],
    },
    {
        "id": "chazeiro", "type": "cura", "region": "picos", "rarity": "raro", "growth": [44, 68],
        "role": "tanque", "behavior": "shy", "gender": "m",
        "concept": "Esqueleto de estalajadeiro de um refúgio dos picos, que serve chá quente a viajantes congelados.",
        "silhouette": "Xícara virada na cabeça; chaleira fumegante com cobertor nos ombros; samovar redondo e alto nas costas soltando vapor.",
        "arc": "Bebê com uma xícara na cabeça → Adolescente enrolado num cobertor, com uma chaleira fumegante → Adulto com um samovar nas costas soltando vapor curativo.",
        "personality": "Acolhedor, lento, hospitaleiro",
        "signature": {"id": "cha_de_abrigo", "pt": "Chá de Abrigo", "en": "Shelter Tea", "es": "Té de Refugio"},
        "stages": [
            {"pt": "Xicrim", "en": "Cuplet", "es": "Tacita",
             "entry": {"pt": "Usa a xícara de chapéu e oferece chá imaginário a quem passa.",
                       "en": "It wears a teacup as a hat and offers imaginary tea to passersby.",
                       "es": "Usa la taza de sombrero y ofrece té imaginario a quien pasa."}},
            {"pt": "Chaleirel", "en": "Kettleby", "es": "Teterón",
             "entry": {"pt": "A chaleira dele assobia quando alguém por perto está com frio.",
                       "en": "Its kettle whistles whenever someone nearby is cold.",
                       "es": "Su tetera silba cuando alguien cerca tiene frío."}},
            {"pt": "Samovarão", "en": "Samovaron", "es": "Samovarón",
             "entry": {"pt": "O vapor do samovar derrete a neve num raio de dez passos. Nenhum viajante congela perto dele.",
                       "en": "The steam from its samovar melts snow ten paces around. No traveler freezes near it.",
                       "es": "El vapor de su samovar derrite la nieve en diez pasos a la redonda. Ningún viajero se congela cerca de él."}},
        ],
    },
    # ------------------------------------------------------------ DESERTO DOS ECOS (Ato 6)
    {
        "id": "domador_escorpioes", "type": "veneno", "region": "deserto", "rarity": "comum", "growth": [44, 68],
        "role": "veloz", "behavior": "chase", "gender": "m",
        "concept": "Esqueleto de domador de escorpiões das caravanas do Deserto dos Ecos.",
        "silhouette": "Cauda curva com ferrão sobre a cabeça em todos os estágios: de pano, depois um escorpião no ombro, e no adulto um escorpião gigante unido às costas.",
        "arc": "Bebê com uma cauda de escorpião de pano presa no capuz → Adolescente com um escorpião vivo no ombro e um chicote → Adulto unido a um escorpião gigante de areia, com o ferrão sobre a cabeça.",
        "personality": "Ousado, exibido, ágil",
        "signature": {"id": "ferrao_das_dunas", "pt": "Ferrão das Dunas", "en": "Dune Sting", "es": "Aguijón de Dunas"},
        "stages": [
            {"pt": "Ferrim", "en": "Stingle", "es": "Aguijín",
             "entry": {"pt": "Finge que a cauda de pano é de verdade e ameaça os outros com ela.",
                       "en": "It pretends its cloth tail is real and threatens others with it.",
                       "es": "Finge que su cola de tela es de verdad y amenaza a los demás con ella."}},
            {"pt": "Escorpeiro", "en": "Whipclaw", "es": "Alacranero",
             "entry": {"pt": "O escorpião do ombro obedece ao estalo do chicote. Na verdade, quem manda é o escorpião.",
                       "en": "The scorpion on its shoulder obeys the crack of its whip. In truth, the scorpion is in charge.",
                       "es": "El escorpión de su hombro obedece al chasquido del látigo. En realidad, quien manda es el escorpión."}},
            {"pt": "Aguilhão", "en": "Venomarch", "es": "Aguijonazo",
             "entry": {"pt": "Já não se sabe onde termina o domador e começa o escorpião. Ataca antes da areia assentar.",
                       "en": "No one can tell where the tamer ends and the scorpion begins. It strikes before the sand settles.",
                       "es": "Ya no se sabe dónde termina el domador y empieza el escorpión. Ataca antes de que la arena se asiente."}},
        ],
    },
    {
        "id": "cartografo", "type": "magico", "region": "deserto", "rarity": "raro", "growth": [48, 70],
        "role": "astuto", "behavior": "shy", "gender": "m",
        "concept": "Esqueleto de cartógrafo do Deserto dos Ecos, que mapeia as dunas ouvindo os ecos.",
        "silhouette": "Instrumento redondo sempre à frente: bússola gigante, depois luneta e rolo de mapa, e no adulto um astrolábio girando em volta do corpo com capa de mapas.",
        "arc": "Bebê abraçado a uma bússola gigante → Adolescente com uma luneta e um rolo de mapa debaixo do braço → Adulto com um astrolábio girando em volta dele e uma capa feita de mapas.",
        "personality": "Curioso, distraído, preciso",
        "signature": {"id": "rota_dos_ecos", "pt": "Rota dos Ecos", "en": "Echo Route", "es": "Ruta de Ecos"},
        "stages": [
            {"pt": "Bussolito", "en": "Compip", "es": "Brujulín",
             "entry": {"pt": "A bússola dele aponta para o lanche mais próximo, não para o norte.",
                       "en": "Its compass points to the nearest snack, not to north.",
                       "es": "Su brújula apunta al bocadillo más cercano, no al norte."}},
            {"pt": "Lunetário", "en": "Scopewright", "es": "Catalejón",
             "entry": {"pt": "Mede as dunas gritando e escutando o eco. Os mapas dele mudam toda vez que venta.",
                       "en": "It measures dunes by shouting and listening to the echo. Its maps change every time the wind blows.",
                       "es": "Mide las dunas gritando y escuchando el eco. Sus mapas cambian cada vez que sopla el viento."}},
            {"pt": "Astrolar", "en": "Astrolux", "es": "Astrolario",
             "entry": {"pt": "O astrolábio gira em volta dele e mostra caminhos que ainda não existem. Nunca se perdeu.",
                       "en": "Its astrolabe spins around it, showing paths that do not exist yet. It has never been lost.",
                       "es": "Su astrolabio gira a su alrededor y muestra caminos que aún no existen. Nunca se ha perdido."}},
        ],
    },
    {
        "id": "tamborileiro", "type": "cura", "region": "deserto", "rarity": "incomum", "growth": [44, 68],
        "role": "equilibrado", "behavior": "circle", "gender": "m",
        "concept": "Esqueleto de tamborileiro das caravanas, cujo ritmo mantém os viajantes de pé no calor do deserto.",
        "silhouette": "Tambor como barriga; o adolescente tem tambores pendurados e baquetas erguidas; o adulto, um grande tambor de dunas nas costas e faixas esvoaçando.",
        "arc": "Bebê com um tamborzinho preso na barriga → Adolescente com tambores pendurados e duas baquetas erguidas → Adulto com um grande tambor de dunas nas costas e faixas coloridas ao vento.",
        "personality": "Animado, rítmico, incansável",
        "signature": {"id": "ritmo_da_caravana", "pt": "Ritmo da Caravana", "en": "Caravan Rhythm", "es": "Ritmo de Caravana"},
        "stages": [
            {"pt": "Tambim", "en": "Drumlet", "es": "Tamborín",
             "entry": {"pt": "Toca a barriga como tambor quando está feliz. Fica feliz com muita facilidade.",
                       "en": "It drums on its belly when it is happy. It gets happy very easily.",
                       "es": "Toca su barriga como tambor cuando está feliz. Se pone feliz con mucha facilidad."}},
            {"pt": "Batucão", "en": "Bongard", "es": "Batucón",
             "entry": {"pt": "Marca o passo das caravanas. Quando ele toca, ninguém sente cansaço.",
                       "en": "It sets the pace for caravans. While it plays, nobody feels tired.",
                       "es": "Marca el paso de las caravanas. Mientras toca, nadie siente cansancio."}},
            {"pt": "Ecoarca", "en": "Echoarch", "es": "Resonarca",
             "entry": {"pt": "O tambor das dunas ecoa por quilômetros. Quem ouve recupera o fôlego, amigo ou inimigo.",
                       "en": "Its dune drum echoes for miles. Whoever hears it catches their breath, friend or foe.",
                       "es": "Su tambor de dunas resuena por kilómetros. Quien lo oye recupera el aliento, amigo o enemigo."}},
        ],
    },
]

# Únicos/raros: não crescem; um por região a partir do Bosque, mais um no Castelo.
UNIQUES = [
    {"id": "raizerno", "type": "cura", "region": "bosque", "role": "tanque", "behavior": "patrol", "gender": "m",
     "concept": "Esqueleto de um eremita tão velho que se fundiu à árvore mais antiga do Bosque das Raízes.",
     "silhouette": "Tronco largo com raízes no lugar das pernas e galhos no lugar dos braços; crânio no meio do tronco.",
     "personality": "Ancestral, paciente, lento",
     "names": {"pt": "Raizerno", "en": "Elderoot", "es": "Raizeño"},
     "entry": {"pt": "Dizem que plantou o Bosque inteiro com uma semente só. Mexe-se uma vez por estação.",
               "en": "It is said to have planted the whole forest from a single seed. It moves once a season.",
               "es": "Dicen que plantó todo el bosque con una sola semilla. Se mueve una vez por estación."}},
    {"id": "vagonauta", "type": "fisico", "region": "minas", "role": "veloz", "behavior": "fast", "gender": "m",
     "concept": "Esqueleto de capataz que nunca saiu do vagonete e corre pelos trilhos abandonados das minas.",
     "silhouette": "Vagonete de mina com rodas; o esqueleto de capacete com lanterna saindo de dentro, braços para frente.",
     "personality": "Afobado, mandão, veloz",
     "names": {"pt": "Vagonauta", "en": "Cartwraith", "es": "Vagonero"},
     "entry": {"pt": "Corre pelos trilhos à noite dando ordens a mineiros que já se foram. O vagonete nunca descarrila.",
               "en": "It races the rails at night shouting orders to miners long gone. Nobody knows how the cart never derails.",
               "es": "Recorre los rieles de noche gritando órdenes a mineros que ya se fueron. Nadie sabe cómo no descarrila."}},
    {"id": "brumaga", "type": "veneno", "region": "pantano", "role": "mago", "behavior": "shy", "gender": "f",
     "concept": "Esqueleto de bruxa da névoa que mora no coração do pântano e cozinha brumas venenosas.",
     "silhouette": "Chapéu pontudo torto e longo, manto em farrapos se desfazendo em névoa, colher de pau gigante.",
     "personality": "Misteriosa, irônica, solitária",
     "names": {"pt": "Brumaga", "en": "Fogmara", "es": "Brumaja"},
     "entry": {"pt": "A névoa do pântano sai do caldeirão dela. Quando ri, o pântano inteiro fica mais denso.",
               "en": "The swamp fog rises from its cauldron. When it laughs, the whole swamp grows thicker.",
               "es": "La niebla del pantano sale de su caldero. Cuando ríe, todo el pantano se vuelve más espeso."}},
    {"id": "bufardo", "type": "magico", "region": "ossorio", "role": "astuto", "behavior": "fast", "gender": "m",
     "concept": "Esqueleto de bobo da corte de Ossório que comanda marionetes com fios mágicos.",
     "silhouette": "Chapéu de bobo de três pontas com guizos; cruzeta de marionete erguida com um bonequinho pendurado.",
     "personality": "Debochado, imprevisível, teatral",
     "names": {"pt": "Bufardo", "en": "Jestrel", "es": "Bufonel"},
     "entry": {"pt": "As marionetes dele imitam quem as olha. Algumas imitam bem demais.",
               "en": "Its puppets mimic whoever watches them. Some mimic far too well.",
               "es": "Sus marionetas imitan a quien las mira. Algunas, demasiado bien."}},
    {"id": "nevasco", "type": "cura", "region": "picos", "role": "suporte", "behavior": "patrol", "gender": "m",
     "concept": "Esqueleto de monge das neves que medita no pico mais alto, coberto por um manto de pelo branco.",
     "silhouette": "Manto peludo branco e largo em forma de montanha; contas de oração; cabeça raspada pequena no topo.",
     "personality": "Sábio, silencioso, bondoso",
     "names": {"pt": "Nevasco", "en": "Blizzabbot", "es": "Nevadón"},
     "entry": {"pt": "Medita há tanto tempo que a neve se acumula nos ombros sem derreter. Uma palavra dele acalma tempestades.",
               "en": "It has meditated so long that snow piles on its shoulders without melting. One word from it calms storms.",
               "es": "Medita desde hace tanto que la nieve se acumula en sus hombros sin derretirse. Una palabra suya calma tormentas."}},
    {"id": "ampulhor", "type": "magico", "region": "deserto", "role": "mago", "behavior": "patrol", "gender": "m",
     "concept": "Esqueleto de guardião das ampulhetas dos templos do Deserto dos Ecos, que mede o tempo em areia.",
     "silhouette": "Toucado de faixas listradas até os ombros; ampulheta grande flutuando acima da mão erguida.",
     "personality": "Solene, impaciente, antigo",
     "names": {"pt": "Ampulhor", "en": "Sandkeeper", "es": "Arenario"},
     "entry": {"pt": "Vira a ampulheta e a batalha fica mais lenta para todos, menos para ele.",
               "en": "When it flips its hourglass, battle slows down for everyone but itself.",
               "es": "Cuando gira su reloj de arena, la batalla se vuelve lenta para todos menos para él."}},
    {"id": "degustor", "type": "veneno", "region": "castelo", "role": "equilibrado", "behavior": "chase", "gender": "m",
     "concept": "Esqueleto do provador oficial do Rei, que provou tantos pratos envenenados que virou o próprio veneno.",
     "silhouette": "Gola alta de corte e uma bandeja coberta (cloche) erguida numa mão; guardanapo no braço.",
     "personality": "Refinado, desconfiado, ácido",
     "names": {"pt": "Degustor", "en": "Tastrel", "es": "Catadón"},
     "entry": {"pt": "Provou cada prato do Rei por cem anos. Hoje é ele quem tempera os inimigos do castelo.",
               "en": "It tasted every royal dish for a hundred years. Now it seasons the castle's enemies.",
               "es": "Probó cada plato del Rey durante cien años. Ahora sazona a los enemigos del castillo."}},
]

KING = {
    "id": "rei_esqueleto", "type": "magico", "region": "castelo", "role": "rei", "behavior": "patrol", "gender": "m",
    "concept": "O Rei Esqueleto, senhor do castelo, que dominou o continente e guarda o segredo de 2040.",
    "silhouette": "Coroa alta de pontas, manto real com gola de pele até o chão, cetro com orbe; o maior sprite do jogo.",
    "personality": "Solitário, imponente, ferido",
    "names": {"pt": "Ossárion", "en": "Ossarion", "es": "Osarión"},
    "entry": {"pt": "O Rei Esqueleto. A coroa dele pesa mais do que deveria, e ninguém nunca perguntou por quê.",
              "en": "The Skeleton King. Its crown weighs more than it should, and nobody ever asked why.",
              "es": "El Rey Esqueleto. Su corona pesa más de lo que debería, y nadie preguntó nunca por qué."},
}

REGION_ORDER = ["praia", "bosque", "minas", "pantano", "ossorio", "picos", "deserto", "castelo"]
REGION_NAMES = {"praia": "Praia do Despertar / Vila Maré", "bosque": "Bosque das Raízes", "minas": "Minas de Cinzas",
                "pantano": "Pântano Verde-Musgo", "ossorio": "Cidade Murada de Ossório", "picos": "Picos Gelados",
                "deserto": "Deserto dos Ecos", "castelo": "Castelo do Rei Esqueleto"}
BEHAVIOR_PT = {"chase": "persegue o jogador", "shy": "tímido (foge)", "circle": "ronda em círculo",
               "patrol": "patrulha", "fast": "rápido"}
TYPE_PT = {"fisico": "Físico", "magico": "Mágico", "cura": "Cura/Suporte", "veneno": "Veneno"}
